# Generated by Django 5.0.4 on 2024-04-08 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='created_at',
            field=models.DateField(help_text='The date and time when the party was created.'),
        ),
    ]
