# Generated by Django 5.0.4 on 2024-04-08 05:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_party_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChineseStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trek_code', models.UUIDField(default=uuid.uuid4, help_text='The Trek code of the product.')),
                ('product_title', models.CharField(help_text='The title of the product.', max_length=100)),
                ('product_count', models.PositiveIntegerField(help_text='The quantity of the product.')),
                ('product_weight', models.FloatField(help_text='The weight of the product.')),
                ('box', models.CharField(help_text='The box of the product.', max_length=100)),
                ('created_at', models.DateField(help_text='The date and time when the product was created.')),
                ('client_keyword', models.ForeignKey(help_text='The keyword of the client.', on_delete=django.db.models.deletion.CASCADE, related_name='chinese_storages', to='app.client')),
                ('party', models.ForeignKey(help_text='The title of the party.', on_delete=django.db.models.deletion.CASCADE, related_name='chinese_storages', to='app.party')),
            ],
        ),
    ]
