# Generated by Django 5.0.4 on 2024-04-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_client_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='given_time',
            field=models.DateField(auto_now_add=True, help_text='The date and time when the client was added to the system.'),
        ),
    ]
